{
  "type": "issue",
  "issue": {
    "id": 2816999140,
    "node_id": "I_kwDOABII586n5_7k",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31754",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31754/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31754/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31754/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/31754",
    "number": 31754,
    "state": "closed",
    "state_reason": "completed",
    "title": "guix SWH vault Internal Server Error",
    "body": "### Is there an existing issue for this?\n\n- [x] I have searched the existing issues\n\n### Current behaviour\n\nFor the first time, running contrib/guix/guix-build, I ran into: \n\n```\nUpdating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...\nSWH: found revision 53396a22afc04536ddf75d8f82ad2eafa5082725 with directory at 'https://archive.softwareheritage.org/api/1/directory/d6d830512c16e46521fab9a956c1842ab2fcdea9/'\nSWH vault: failure: Internal Server Error. This incident will be reported.\nThe full error was:\n\nTraceback (most recent call last):\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/vault/cookers/base.py\", line 135, in cook\n    self.prepare_bundle()\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/vault/cookers/git_bare.py\", line 168, in prepare_bundle\n    self.load_objects()\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/vault/cookers/git_bare.py\", line 413, in load_objects\n    self.load_revisions(revision_ids)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/vault/cookers/git_bare.py\", line 586, in load_revisions\n    ret: List[Optional[Revision]] = self.storage.revision_get(obj_ids)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 336, in wrapped_f\n    return copy(f, *args, **kw)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 475, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 376, in iter\n    result = action(retry_state)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"/opt/swh/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/swh/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 478, in __call__\n    result = fn(*args, **kwargs)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/storage/proxies/retry.py\", line 81, in newf\n    return getattr(storage, attribute_name)(*args, **kwargs)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/core/api/__init__.py\", line 196, in meth_\n    return self._post(meth._endpoint_path, post_data)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/core/api/__init__.py\", line 356, in _post\n    return self._decode_response(response)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/core/api/__init__.py\", line 443, in _decode_response\n    self.raise_for_status(response)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/storage/api/client.py\", line 45, in raise_for_status\n    super().raise_for_status(response)\n  File \"/opt/swh/.local/lib/python3.10/site-packages/swh/core/api/__init__.py\", line 433, in raise_for_status\n    raise exception from None\nswh.core.api.RemoteException: <RemoteException 500 ReadTimeout: ['Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\\' responses] message=\"Operation timed out - received only 1 responses.\" info={\\'consistency\\': \\'LOCAL_QUORUM\\', \\'required_responses\\': 2, \\'received_responses\\': 1}']>\n\nSWH vault: retrying...\nSWH vault: requested bundle cooking, waiting for completion...\n```\nHas anyone else seen this before? Anyone else seeing this? Is it just me? Thank you.\n\n### Expected behaviour\n\nShould compile as normal.\n\n### Steps to reproduce\n\ncontrib/guix/guix-build\n\n### Relevant log output\n\n_No response_\n\n### How did you obtain Bitcoin Core\n\nCompiled from source\n\n### What version of Bitcoin Core are you using?\n\ncommit b432e367427f1f9fe0f0a5800e31e496f00cd38d\n\n### Operating system and version\n\nUbuntu 24.04.1 LTS\n\n### Machine specifications\n\nancient machine, but good Ubuntu.\n\n$ guix --version\nguix (GNU Guix) 1.4.0\nCopyright (C) 2022 the Guix authors\n\n",
    "user": {
      "login": "tofutim",
      "id": 157766,
      "node_id": "MDQ6VXNlcjE1Nzc2Ng==",
      "avatar_url": "https://avatars.githubusercontent.com/u/157766?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tofutim",
      "html_url": "https://github.com/tofutim",
      "followers_url": "https://api.github.com/users/tofutim/followers",
      "following_url": "https://api.github.com/users/tofutim/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/tofutim/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/tofutim/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/tofutim/subscriptions",
      "organizations_url": "https://api.github.com/users/tofutim/orgs",
      "repos_url": "https://api.github.com/users/tofutim/repos",
      "events_url": "https://api.github.com/users/tofutim/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/tofutim/received_events",
      "type": "User",
      "site_admin": false,
      "patch_url": null
    },
    "labels": [
      {
        "id": 159815356,
        "node_id": "MDU6TGFiZWwxNTk4MTUzNTY=",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Upstream",
        "name": "Upstream",
        "color": "bfd4f2",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "NONE",
    "locked": false,
    "comments": 1,
    "closed_at": "2025-01-29T09:34:08Z",
    "closed_by": {
      "login": "fanquake",
      "id": 863730,
      "node_id": "MDQ6VXNlcjg2MzczMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fanquake",
      "html_url": "https://github.com/fanquake",
      "followers_url": "https://api.github.com/users/fanquake/followers",
      "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
      "organizations_url": "https://api.github.com/users/fanquake/orgs",
      "repos_url": "https://api.github.com/users/fanquake/repos",
      "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/fanquake/received_events",
      "type": "User",
      "site_admin": false,
      "patch_url": null
    },
    "created_at": "2025-01-29T00:50:47Z",
    "updated_at": "2025-01-29T09:34:10Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 16105026282,
      "node_id": "LE_lADOABII586n5_7kzwAAAAO_7zLq",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/16105026282",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-01-29T09:33:35Z",
      "label": {
        "name": "Upstream",
        "color": "bfd4f2"
      }
    },
    {
      "event": "commented",
      "id": 2621122709,
      "node_id": "IC_kwDOABII586cOyiV",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2621122709",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-01-29T09:34:09Z",
      "updated_at": "2025-01-29T09:34:09Z",
      "author_association": "MEMBER",
      "body": "I haven't seen this before, but it looks like a (hopefully intermittent) upstream issue.",
      "user": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/31754#issuecomment-2621122709",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31754"
    },
    {
      "event": "closed",
      "id": 16105033309,
      "node_id": "CE_lADOABII586n5_7kzwAAAAO_705d",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/16105033309",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-01-29T09:34:09Z"
    }
  ]
}